### ISSUE TITLE
Add support for Gradle kotlin syntax

### ISSUE THREAD

**Issue by SpiReCZ** [jirkapinkas/javalibs#14]
Javalibs supports a lot of package managers that are probably less used overall than the new Gradle Kotlin DSL one.

Gradle Kotlin DSL syntax:
`implementation("org.bouncycastle:bcprov-jdk15on:1.66")`

Gradle Groovy DSL syntax:
`implementation 'org.bouncycastle:bcprov-jdk15on:1.66'`

**I suggest adding it and changing the order of Gradle as it is more popular than Ivy.** (Maven, Gradle, Ivy, ...)

New Gradle tab example:
<img width="424" alt="Snímek obrazovky 2020-11-01 v 11 08 41" src="https://user-images.githubusercontent.com/15370999/97800108-7d38a300-1c2a-11eb-95a1-52422d28b642.png">

Code example:
```
Gradle Kotlin DSL syntax:
<textarea class="form-control autoselect" rows="1" onclick="App.copyToClipboard()" wrap="off">implementation("org.bouncycastle:bcprov-jdk15on:1.66")</textarea>
<br>
Gradle Groovy DSL syntax:
<textarea class="form-control autoselect" rows="1" onclick="App.copyToClipboard()" wrap="off">implementation 'org.bouncycastle:bcprov-jdk15on:1.66'</textarea>
```

**Comment by jirkapinkas** [comment]
DONE ;-)
