### ISSUE TITLE
Add information about vulnerabilities from snyk.io

### ISSUE THREAD

**Issue by hkrizek** [jirkapinkas/javalibs#15]
Add information about vulnerability from snyk.io e.g. https://snyk.io/vuln/maven:com.hazelcast%3Ahazelcast
or from other source if snyk.io api is not publicly available (or can it be scraped ? )

**Comment by jirkapinkas** [comment]
Unfortunately it's not possible to get data from snyk directly to javalibs pages, but at least I did add a link to every artifact so that it's possible to easily navigate to snyk's database
