### ISSUE TITLE
javalibs Site is down

### ISSUE THREAD

**Issue by masterElmar** [jirkapinkas/javalibs#16]
I don't know if this is important, but this site suggests writing a report when it's longer down.
https://javalibs.com/

**Comment by jirkapinkas** [comment]
Yeah, sorry about that. Yesterday server which is running site unrecoverably crashed, and I was forced to perform full restore from backup and it's taking longer than expected (but I've never had to do this, so I had no idea what to expect :-) ). Anyways, hopefully it will be up and running soon-ish. Sorry for the inconvenience. Cheers. JP
