### ISSUE TITLE
Add JCenter as source

### ISSUE THREAD

**Issue by juherr** [jirkapinkas/javalibs#3]
JCenter is a mirror of Maven Central but contains more artifacts too: https://bintray.com/bintray/jcenter/

**Comment by jirkapinkas** [comment]
Would love to, but JCenter isn't very much "hacker friendly" and that's the reason why I've been avoiding it so far. Also javalibs has most of the libraries from jcenter already (for the most part jcenter just aggregates several open source Maven repositories). But I'll try to get their consent to track them.
