### ISSUE TITLE
Search panel překrývá javadoc

### ISSUE THREAD

**Issue by radekerben** [jirkapinkas/javalibs#9]
Ahoj jirko,
při kliku na javadoc/javasource a zapnutým dark mode. Tak search panel překrývá panel toho javadocu.
viz screenshot
https://javalibs.com/artifact/no.tornado/tornadofx
<img width="1112" alt="screenshot 2019-02-07 at 10 13 10" src="https://user-images.githubusercontent.com/6839904/52401034-0d32d280-2ac1-11e9-8e23-9792662e3581.png">

**Comment by jirkapinkas** [comment]
Tak toho jsem si ani nevšiml :-) Opraveno. Btw: doufám, že se temný vzhled líbí ;-)

**Comment by radekerben** [comment]
Jop, sice ta zelená je tam trochu rušivá, možná zvolit tmavší odstín.
Jinak spokojenost, jsem rád za jakýkoliv dark mode. Kdekoliv. 👍
